import type { number2, boolean2, number3, boolean3, number4, boolean4, numberQ, number2x2, number3x3, number4x4, color, colorX, color32 } from "./primitives.ts"

// AUTOGENERATED!!! Modify the matching file in /generators

export type PrimitiveType = "byte"|"ushort"|"uint"|"ulong"|"sbyte"|"short"|"int"|"long"|"float"|"double"|"decimal"|"bool"|"char"|"string"|"Uri"|"DateTime"|"TimeSpan"|"color"|"colorX"|"color32"|"float2"|"double2"|"byte2"|"ushort2"|"uint2"|"ulong2"|"sbyte2"|"short2"|"int2"|"long2"|"bool2"|"float3"|"double3"|"byte3"|"ushort3"|"uint3"|"ulong3"|"sbyte3"|"short3"|"int3"|"long3"|"bool3"|"float4"|"double4"|"byte4"|"ushort4"|"uint4"|"ulong4"|"sbyte4"|"short4"|"int4"|"long4"|"bool4"|"floatQ"|"doubleQ"|"float2x2"|"double2x2"|"float3x3"|"double3x3"|"float4x4"|"double4x4"
export type NullableType = "byte?"|"ushort?"|"uint?"|"ulong?"|"sbyte?"|"short?"|"int?"|"long?"|"float?"|"double?"|"decimal?"|"bool?"|"char?"|"DateTime?"|"TimeSpan?"|"color?"|"colorX?"|"color32?"|"float2?"|"double2?"|"byte2?"|"ushort2?"|"uint2?"|"ulong2?"|"sbyte2?"|"short2?"|"int2?"|"long2?"|"bool2?"|"float3?"|"double3?"|"byte3?"|"ushort3?"|"uint3?"|"ulong3?"|"sbyte3?"|"short3?"|"int3?"|"long3?"|"bool3?"|"float4?"|"double4?"|"byte4?"|"ushort4?"|"uint4?"|"ulong4?"|"sbyte4?"|"short4?"|"int4?"|"long4?"|"bool4?"|"floatQ?"|"doubleQ?"|"float2x2?"|"double2x2?"|"float3x3?"|"double3x3?"|"float4x4?"|"double4x4?"
export type FieldType = PrimitiveType | NullableType | "enum" | "enum?"

export type ArrayType = "byte[]"|"ushort[]"|"uint[]"|"ulong[]"|"sbyte[]"|"short[]"|"int[]"|"long[]"|"float[]"|"double[]"|"decimal[]"|"bool[]"|"char[]"|"string[]"|"Uri[]"|"DateTime[]"|"TimeSpan[]"|"color[]"|"colorX[]"|"color32[]"|"float2[]"|"double2[]"|"byte2[]"|"ushort2[]"|"uint2[]"|"ulong2[]"|"sbyte2[]"|"short2[]"|"int2[]"|"long2[]"|"bool2[]"|"float3[]"|"double3[]"|"byte3[]"|"ushort3[]"|"uint3[]"|"ulong3[]"|"sbyte3[]"|"short3[]"|"int3[]"|"long3[]"|"bool3[]"|"float4[]"|"double4[]"|"byte4[]"|"ushort4[]"|"uint4[]"|"ulong4[]"|"sbyte4[]"|"short4[]"|"int4[]"|"long4[]"|"bool4[]"|"floatQ[]"|"doubleQ[]"|"float2x2[]"|"double2x2[]"|"float3x3[]"|"double3x3[]"|"float4x4[]"|"double4x4[]"

export type ResoToTS<T extends FieldType | ArrayType> = {
"byte": number
"byte[]": number[]
"byte?": number | null
"ushort": number
"ushort[]": number[]
"ushort?": number | null
"uint": number
"uint[]": number[]
"uint?": number | null
"ulong": number
"ulong[]": number[]
"ulong?": number | null
"sbyte": number
"sbyte[]": number[]
"sbyte?": number | null
"short": number
"short[]": number[]
"short?": number | null
"int": number
"int[]": number[]
"int?": number | null
"long": number
"long[]": number[]
"long?": number | null
"float": number
"float[]": number[]
"float?": number | null
"double": number
"double[]": number[]
"double?": number | null
"decimal": number
"decimal[]": number[]
"decimal?": number | null
"bool": boolean
"bool[]": boolean[]
"bool?": boolean | null
"char": string
"char[]": string[]
"char?": string | null
"string": string | null
"string[]": (string | null)[]
"Uri": string
"Uri[]": string[]
"DateTime": string
"DateTime[]": string[]
"DateTime?": string | null
"TimeSpan": string
"TimeSpan[]": string[]
"TimeSpan?": string | null
"color": color
"color[]": color[]
"color?": color | null
"colorX": colorX
"colorX[]": colorX[]
"colorX?": colorX | null
"color32": color32
"color32[]": color32[]
"color32?": color32 | null
"float2": number2
"float2[]": number2[]
"float2?": number2 | null
"double2": number2
"double2[]": number2[]
"double2?": number2 | null
"byte2": number2
"byte2[]": number2[]
"byte2?": number2 | null
"ushort2": number2
"ushort2[]": number2[]
"ushort2?": number2 | null
"uint2": number2
"uint2[]": number2[]
"uint2?": number2 | null
"ulong2": number2
"ulong2[]": number2[]
"ulong2?": number2 | null
"sbyte2": number2
"sbyte2[]": number2[]
"sbyte2?": number2 | null
"short2": number2
"short2[]": number2[]
"short2?": number2 | null
"int2": number2
"int2[]": number2[]
"int2?": number2 | null
"long2": number2
"long2[]": number2[]
"long2?": number2 | null
"bool2": boolean2
"bool2[]": boolean2[]
"bool2?": boolean2 | null
"float3": number3
"float3[]": number3[]
"float3?": number3 | null
"double3": number3
"double3[]": number3[]
"double3?": number3 | null
"byte3": number3
"byte3[]": number3[]
"byte3?": number3 | null
"ushort3": number3
"ushort3[]": number3[]
"ushort3?": number3 | null
"uint3": number3
"uint3[]": number3[]
"uint3?": number3 | null
"ulong3": number3
"ulong3[]": number3[]
"ulong3?": number3 | null
"sbyte3": number3
"sbyte3[]": number3[]
"sbyte3?": number3 | null
"short3": number3
"short3[]": number3[]
"short3?": number3 | null
"int3": number3
"int3[]": number3[]
"int3?": number3 | null
"long3": number3
"long3[]": number3[]
"long3?": number3 | null
"bool3": boolean3
"bool3[]": boolean3[]
"bool3?": boolean3 | null
"float4": number4
"float4[]": number4[]
"float4?": number4 | null
"double4": number4
"double4[]": number4[]
"double4?": number4 | null
"byte4": number4
"byte4[]": number4[]
"byte4?": number4 | null
"ushort4": number4
"ushort4[]": number4[]
"ushort4?": number4 | null
"uint4": number4
"uint4[]": number4[]
"uint4?": number4 | null
"ulong4": number4
"ulong4[]": number4[]
"ulong4?": number4 | null
"sbyte4": number4
"sbyte4[]": number4[]
"sbyte4?": number4 | null
"short4": number4
"short4[]": number4[]
"short4?": number4 | null
"int4": number4
"int4[]": number4[]
"int4?": number4 | null
"long4": number4
"long4[]": number4[]
"long4?": number4 | null
"bool4": boolean4
"bool4[]": boolean4[]
"bool4?": boolean4 | null
"floatQ": numberQ
"floatQ[]": numberQ[]
"floatQ?": numberQ | null
"doubleQ": numberQ
"doubleQ[]": numberQ[]
"doubleQ?": numberQ | null
"float2x2": number2x2
"float2x2[]": number2x2[]
"float2x2?": number2x2 | null
"double2x2": number2x2
"double2x2[]": number2x2[]
"double2x2?": number2x2 | null
"float3x3": number3x3
"float3x3[]": number3x3[]
"float3x3?": number3x3 | null
"double3x3": number3x3
"double3x3[]": number3x3[]
"double3x3?": number3x3 | null
"float4x4": number4x4
"float4x4[]": number4x4[]
"float4x4?": number4x4 | null
"double4x4": number4x4
"double4x4[]": number4x4[]
"double4x4?": number4x4 | null
"enum": string
"enum?": string | null
}[T]

const equivalentTypes: Record<string, string> = {
"byte": "number",
"byte[]": "number[]",
"byte?": "number | null",
"ushort": "number",
"ushort[]": "number[]",
"ushort?": "number | null",
"uint": "number",
"uint[]": "number[]",
"uint?": "number | null",
"ulong": "number",
"ulong[]": "number[]",
"ulong?": "number | null",
"sbyte": "number",
"sbyte[]": "number[]",
"sbyte?": "number | null",
"short": "number",
"short[]": "number[]",
"short?": "number | null",
"int": "number",
"int[]": "number[]",
"int?": "number | null",
"long": "number",
"long[]": "number[]",
"long?": "number | null",
"float": "number",
"float[]": "number[]",
"float?": "number | null",
"double": "number",
"double[]": "number[]",
"double?": "number | null",
"decimal": "number",
"decimal[]": "number[]",
"decimal?": "number | null",
"bool": "boolean",
"bool[]": "boolean[]",
"bool?": "boolean | null",
"char": "string",
"char[]": "string[]",
"char?": "string | null",
"string": "string | null",
"string[]": "(string | null)[]",
"Uri": "string",
"Uri[]": "string[]",
"DateTime": "string",
"DateTime[]": "string[]",
"DateTime?": "string | null",
"TimeSpan": "string",
"TimeSpan[]": "string[]",
"TimeSpan?": "string | null",
"color": "color",
"color[]": "color[]",
"color?": "color | null",
"colorX": "colorX",
"colorX[]": "colorX[]",
"colorX?": "colorX | null",
"color32": "color32",
"color32[]": "color32[]",
"color32?": "color32 | null",
"float2": "number2",
"float2[]": "number2[]",
"float2?": "number2 | null",
"double2": "number2",
"double2[]": "number2[]",
"double2?": "number2 | null",
"byte2": "number2",
"byte2[]": "number2[]",
"byte2?": "number2 | null",
"ushort2": "number2",
"ushort2[]": "number2[]",
"ushort2?": "number2 | null",
"uint2": "number2",
"uint2[]": "number2[]",
"uint2?": "number2 | null",
"ulong2": "number2",
"ulong2[]": "number2[]",
"ulong2?": "number2 | null",
"sbyte2": "number2",
"sbyte2[]": "number2[]",
"sbyte2?": "number2 | null",
"short2": "number2",
"short2[]": "number2[]",
"short2?": "number2 | null",
"int2": "number2",
"int2[]": "number2[]",
"int2?": "number2 | null",
"long2": "number2",
"long2[]": "number2[]",
"long2?": "number2 | null",
"bool2": "boolean2",
"bool2[]": "boolean2[]",
"bool2?": "boolean2 | null",
"float3": "number3",
"float3[]": "number3[]",
"float3?": "number3 | null",
"double3": "number3",
"double3[]": "number3[]",
"double3?": "number3 | null",
"byte3": "number3",
"byte3[]": "number3[]",
"byte3?": "number3 | null",
"ushort3": "number3",
"ushort3[]": "number3[]",
"ushort3?": "number3 | null",
"uint3": "number3",
"uint3[]": "number3[]",
"uint3?": "number3 | null",
"ulong3": "number3",
"ulong3[]": "number3[]",
"ulong3?": "number3 | null",
"sbyte3": "number3",
"sbyte3[]": "number3[]",
"sbyte3?": "number3 | null",
"short3": "number3",
"short3[]": "number3[]",
"short3?": "number3 | null",
"int3": "number3",
"int3[]": "number3[]",
"int3?": "number3 | null",
"long3": "number3",
"long3[]": "number3[]",
"long3?": "number3 | null",
"bool3": "boolean3",
"bool3[]": "boolean3[]",
"bool3?": "boolean3 | null",
"float4": "number4",
"float4[]": "number4[]",
"float4?": "number4 | null",
"double4": "number4",
"double4[]": "number4[]",
"double4?": "number4 | null",
"byte4": "number4",
"byte4[]": "number4[]",
"byte4?": "number4 | null",
"ushort4": "number4",
"ushort4[]": "number4[]",
"ushort4?": "number4 | null",
"uint4": "number4",
"uint4[]": "number4[]",
"uint4?": "number4 | null",
"ulong4": "number4",
"ulong4[]": "number4[]",
"ulong4?": "number4 | null",
"sbyte4": "number4",
"sbyte4[]": "number4[]",
"sbyte4?": "number4 | null",
"short4": "number4",
"short4[]": "number4[]",
"short4?": "number4 | null",
"int4": "number4",
"int4[]": "number4[]",
"int4?": "number4 | null",
"long4": "number4",
"long4[]": "number4[]",
"long4?": "number4 | null",
"bool4": "boolean4",
"bool4[]": "boolean4[]",
"bool4?": "boolean4 | null",
"floatQ": "numberQ",
"floatQ[]": "numberQ[]",
"floatQ?": "numberQ | null",
"doubleQ": "numberQ",
"doubleQ[]": "numberQ[]",
"doubleQ?": "numberQ | null",
"float2x2": "number2x2",
"float2x2[]": "number2x2[]",
"float2x2?": "number2x2 | null",
"double2x2": "number2x2",
"double2x2[]": "number2x2[]",
"double2x2?": "number2x2 | null",
"float3x3": "number3x3",
"float3x3[]": "number3x3[]",
"float3x3?": "number3x3 | null",
"double3x3": "number3x3",
"double3x3[]": "number3x3[]",
"double3x3?": "number3x3 | null",
"float4x4": "number4x4",
"float4x4[]": "number4x4[]",
"float4x4?": "number4x4 | null",
"double4x4": "number4x4",
"double4x4[]": "number4x4[]",
"double4x4?": "number4x4 | null",
"enum": "string",
"enum?": "string | null",
}

/** Get the corresponding TS type string from a Resonite type string.
 * This only includes Field and Array types. `"list"` and `"syncObject"` will return `undefined` 
 * 
 * Note : strings in Resonite are always nullable. (`"string"` -> `"string | null"`)
 * 
 * See also `isNullableType`, `isArrayType`, `getPrimitiveType`. */
export function getTsTypeFromResoniteType(type: string): string {
    return equivalentTypes[type]
}
